name: "Update Flake Lock"
on:
  schedule:
    # Update at 1:30am daily
    - cron: '30 1 * * *'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  update:
    name: "Update flake inputs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          enable_kvm: false
          install_options: --no-daemon
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        # Needed for the "gh pr merge"
        id: update-flake-lock
        with:
          commit-msg: "chore(deps): update `flake.lock`"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: | # Labels to be set on the PR
            automated
            dependencies
          pr-title: "chore(deps): update `flake.lock`"

      - name: Enable Pull Request Automerge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --rebase --auto "${{ steps.update-flake-lock.outputs.pull-request-number }}"
